version: "3.9"
services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    networks:
      - internal
    volumes:
      - ./docker/dev/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./patch_server:/var/www/html
      - ./logs:/var/log/nginx
    depends_on:
      - php
  php:
    build: 
      context: ./docker/dev/php
    networks:
      - internal
    volumes:
      - ./patch_server:/var/www/html
  filebrowser:
    image: filebrowser/filebrowser
    ports:
      - 8188:80
    volumes:
      - ./config:/config
      - ./patch_server:/srv
networks:
  internal:
    driver: bridge